import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "./components/SiteHeader";
import SiteFooter from "./components/SiteFooter";
import AppShell from "./components/AppShell";
import SideBar from "./components/SideBar";
import localFont from "next/font/local";
import Robot from "./components/RobotEmoji"
import { StuckAssistantProvider } from "./providers/stuck-assistance-provider";
import Providers from "./providers";
import StuckModal from "@/app/components/AIHelp";
export const dsDigital = localFont({
  src: [
    {
      path: "../public/fonts/ds_digital/DS-DIGI.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/ds_digital/DS-DIGIB.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/ds_digital/DS-DIGII.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/ds_digital/DS-DIGIT.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-ds-digital",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={dsDigital.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <div className="flex flex-col min-h-screen">
          <SiteHeader />
          <StuckAssistantProvider>
          <AppShell>{children}</AppShell>
          <Robot />
          </StuckAssistantProvider>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
