import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "./components/SiteHeader";
import SiteFooter from "./components/SiteFooter";
import SideBar from "./components/SideBar";
import localFont from "next/font/local";

const dsDigital = localFont({
  src: [
    {
      path: "../fonts/ds_digital/DS-DIGI.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/ds_digital/DS-DIGIB.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/ds_digital/DS-DIGII.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/ds_digital/DS-DIGIT.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-ds-digital",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <SiteHeader />

        <div className="flex flex-1">
          <SideBar />
          <main className="flex-1">
            {children}
          </main>
        </div>

        <SiteFooter />
      </body>
    </html>
  );
}
